### ISSUE TITLE
Add support for exporting saved chats (HTML elements differ)

### ISSUE THREAD

**Issue by phobozad** [jcubic/chat-gpt#2]
With the addition of multiple chat/history support on ChatGPT, this script seems to break if you want to export a previous chat that is saved instead of a fresh new/live chat.

This seems to be an issue with the HTML classes in use which differ between a live chat session and a non-live session.

The script is looking for classes starting with `react-scroll-to-bottom` but this class apparently isn't used with the new multiple chat feature.

I'm not sure the proper elements to use or the best way to select them, but here is a hacky way I've used which at least demonstrates the difference in classes/elements/structure.  Clearly I'm not super experienced with proper CSS markup.  😅 

### Query Selector
```javascript
document.querySelector('main > .flex-1 > .h-full').innerHTML
```

### Styles
(dropped `react-scroll-to-bottom` and added `.text-base`)

```css
.flex > div:nth-child(2n+1) .text-base {
    background: lightgray;
}
.flex > div:nth-child(2n+2) .text-base{
    background: darkgray;
}
.flex > div:not(:last-child) .text-base{
    padding: 10px;
    margin: 10px;
    border-radius: 5px;
}
.items-end {
  display: none !important;
}
```
